name: BetterChatColours
main: io.imadam.betterchatcolours.BetterChatColours
version: 1.0.0
api-version: 1.19
depend: [PlaceholderAPI]

commands:
  chatcolors:
    description: Access chat color presets
    aliases: [cc, chatcolor]
    permission: betterchatcolours.use
    usage: /<command> [admin]

permissions:
  chatcolor.use:
    description: Use basic chat color features
    default: true
  chatcolor.admin:
    description: Manage global presets
    default: op
  chatcolor.preset.*:
    description: Access to all presets
    default: op
